# Generated by Django 3.2 on 2021-05-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210416_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
